addons:
  sauce_connect:
    username: "aikrasnov"
    access_key: "e6968af3-55c0-455e-b712-f6ef086f5640"

language: python
python: 3.7
dist: xenial
sudo: true
script:
    - pip install pipenv
    - pipenv install
    - pipenv shell
    - pipenv run pytest
